# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Cameron Meyer Portfolio
email: cameron.meyer02@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The technical art portfolio for developer Cameron Meyer.
#url: https://utdsgda.club # the base hostname & protocol of the site

## Data variables
footer_menu: footer # Storing footer.yml as a variable

## Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: _pages
    values:
      layout: default

# Compress.html (html minifier)
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

include: ["_pages", "_redirects", "assets/css"]
exclude: ["README.md"]